// Türkçe küfür/argo kara listesi — ikinci katman öncesi hızlı, ücretsiz filtre.
// Kaynak: ooguz/turkce-kufur-karaliste (CC BY-SA 4.0), https://github.com/ooguz/turkce-kufur-karaliste
// Dini/nötr kelimeler (ör. "allah", "ahmak") ve iki harfli aşırı geniş eşleşen
// girdiler yanlış-pozitifleri önlemek için listeden çıkarıldı. NIM tabanlı
// sınıflandırma (moderation.js) asıl anlamsal denetimi yapan ikinci katmandır.
const BLOCKED_WORDS = [
  "a.q",
  "a.q.",
  "abaza",
  "abazan",
  "am biti",
  "amarım",
  "ambiti",
  "amcik",
  "amck",
  "amckl",
  "amcklama",
  "amcklaryla",
  "amckta",
  "amcktan",
  "amcuk",
  "amcık",
  "amcık hoşafı",
  "amcıklama",
  "amcıklandı",
  "amcığı",
  "amcığın",
  "amcığını",
  "amcığınızı",
  "amin oglu",
  "amina",
  "amina g",
  "amina k",
  "amina koyarim",
  "amina koyayim",
  "amina koyayım",
  "aminako",
  "aminakoyarim",
  "aminakoyim",
  "aminda",
  "amindan",
  "amindayken",
  "amini",
  "aminiyarraaniskiim",
  "aminoglu",
  "amiyum",
  "amk",
  "amk çocuğu",
  "amkafa",
  "amlarnzn",
  "amlı",
  "amm",
  "ammak",
  "ammna",
  "amn",
  "amna",
  "amnda",
  "amndaki",
  "amngtn",
  "amnn",
  "amona",
  "amq",
  "amsiz",
  "amsz",
  "amsız",
  "amteri",
  "amugaa",
  "amuna",
  "amuğa",
  "amık",
  "amın feryadı",
  "amın oglu",
  "amın oğlu",
  "amına",
  "amına koy",
  "amına koyarım",
  "amına koyayım",
  "amına koyyim",
  "amına s",
  "amına sikem",
  "amına sokam",
  "amınako",
  "amınakoyim",
  "amınoğlu",
  "amını",
  "amını s",
  "amısına",
  "amısını",
  "anaaann",
  "anal",
  "analarn",
  "anamla",
  "anandan",
  "anani sikerim",
  "anani sikeyim",
  "ananin",
  "ananisikerim",
  "ananisikeyim",
  "ananı sikerim",
  "ananı sikeyim",
  "ananın",
  "ananın am",
  "ananın amı",
  "ananın dölü",
  "ananınki",
  "ananısikerim",
  "ananısikeyim",
  "ananızın",
  "ananızın am",
  "anasinin",
  "anası orospu",
  "anasını",
  "anasının am",
  "anayin",
  "angut",
  "anneni",
  "annenin",
  "annesiz",
  "anuna",
  "aptal",
  "aq",
  "aq.",
  "atkafası",
  "atmık",
  "attrrm",
  "attırdığım",
  "auzlu",
  "avrat",
  "ayklarmalrmsikerim",
  "azdım",
  "azdır",
  "azdırıcı",
  "ağzına sıçayım",
  "babaannesi kaşar",
  "babani",
  "babanı",
  "babanın",
  "babası pezevenk",
  "bacağına sıçayım",
  "bacini",
  "bacndan",
  "bacına",
  "bacını",
  "bacının",
  "bastard",
  "basur",
  "beyinsiz",
  "bitch",
  "biting",
  "bok",
  "boka",
  "bokbok",
  "bokhu",
  "bokkkumu",
  "boklar",
  "boktan",
  "boku",
  "bokubokuna",
  "bokum",
  "bokça",
  "bombok",
  "boner",
  "bosalmak",
  "boşalmak",
  "bızır",
  "cenabet",
  "cibiliyetsiz",
  "cibilliyetini",
  "cibilliyetsiz",
  "cikar",
  "dalaksız",
  "dallama",
  "daltassak",
  "dalyarak",
  "dalyarrak",
  "dangalak",
  "dassagi",
  "diktim",
  "dildo",
  "dingil",
  "dingilini",
  "dinsiz",
  "dkerim",
  "domal",
  "domalan",
  "domaldı",
  "domaldın",
  "domalmak",
  "domalmış",
  "domalsın",
  "domalt",
  "domaltarak",
  "domaltip",
  "domaltmak",
  "domaltıp",
  "domaltır",
  "domaltırım",
  "domalık",
  "domalıyor",
  "dölü",
  "dönek",
  "düdük",
  "eben",
  "ebeni",
  "ebenin",
  "ebeninki",
  "ebleh",
  "ecdadini",
  "ecdadını",
  "embesil",
  "fahise",
  "fahişe",
  "feriştah",
  "ferre",
  "fuck",
  "fucker",
  "fuckin",
  "fucking",
  "gavad",
  "gavat",
  "geber",
  "geberik",
  "gebermek",
  "gebermiş",
  "gebertir",
  "gerizekali",
  "gerizekalı",
  "gerzek",
  "gerızekalı",
  "giberim",
  "giberler",
  "gibis",
  "gibiş",
  "gibmek",
  "gibtiler",
  "goddamn",
  "godoş",
  "godumun",
  "gotelek",
  "gotlalesi",
  "gotlu",
  "gotten",
  "gotundeki",
  "gotunden",
  "gotune",
  "gotunu",
  "gotveren",
  "goyiim",
  "goyum",
  "goyuyim",
  "goyyim",
  "gtelek",
  "gtn",
  "gtnde",
  "gtnden",
  "gtne",
  "gtten",
  "gtveren",
  "göt",
  "göt deliği",
  "göt herif",
  "göt oğlanı",
  "göt veren",
  "göt verir",
  "götelek",
  "götlalesi",
  "götlek",
  "götoğlanı",
  "götoş",
  "götten",
  "götveren",
  "götü",
  "götün",
  "götüne",
  "götüne koyim",
  "götünekoyim",
  "götünü",
  "has siktir",
  "hasiktir",
  "hassikome",
  "hassiktir",
  "hassittir",
  "haysiyetsiz",
  "hayvan herif",
  "hoşafı",
  "hsktr",
  "huur",
  "hödük",
  "ibina",
  "ibine",
  "ibinenin",
  "ibne",
  "ibnedir",
  "ibneleri",
  "ibnelik",
  "ibnelri",
  "ibneni",
  "ibnenin",
  "ibnerator",
  "ibnesi",
  "idiot",
  "idiyot",
  "imansz",
  "ipne",
  "iserim",
  "itoğlu it",
  "işerim",
  "kafam girsin",
  "kafasiz",
  "kafasız",
  "kahpe",
  "kahpenin",
  "kahpenin feryadı",
  "kaka",
  "kaltak",
  "kancik",
  "kancık",
  "kappe",
  "karhane",
  "kavat",
  "kavatn",
  "kaypak",
  "kayyum",
  "kaşar",
  "kerane",
  "kerhane",
  "kerhanelerde",
  "kevase",
  "kevaşe",
  "kevvase",
  "koca göt",
  "kodumun",
  "kodumunun",
  "koduumun",
  "koduğmun",
  "koduğmunun",
  "koyarm",
  "koyayım",
  "koyiim",
  "koyiiym",
  "koyim",
  "koyum",
  "koyyim",
  "kukudaym",
  "laciye boyadım",
  "lavuk",
  "liboş",
  "madafaka",
  "mal",
  "malafat",
  "malak",
  "manyak",
  "mcik",
  "meme",
  "memelerini",
  "mezveleli",
  "minaamcık",
  "mincikliyim",
  "monakkoluyum",
  "motherfucker",
  "mudik",
  "o. çocuğu",
  "ocuu",
  "ocuun",
  "orosbucocuu",
  "orospu",
  "orospu cocugu",
  "orospu çoc",
  "orospu çocukları",
  "orospu çocuğu",
  "orospu çocuğudur",
  "orospucocugu",
  "orospudur",
  "orospular",
  "orospunun",
  "orospunun evladı",
  "orospuydu",
  "orospuyuz",
  "orospuçocuğu",
  "orostoban",
  "orostopol",
  "orrospu",
  "oruspu",
  "oruspu çocuğu",
  "oruspuçocuğu",
  "osbir",
  "ossurduum",
  "ossurmak",
  "ossuruk",
  "osur",
  "osurduu",
  "osuruk",
  "osururum",
  "otuzbir",
  "oç",
  "oğlan",
  "oğlancı",
  "oğlu it",
  "patlak zar",
  "penis",
  "pezevek",
  "pezeven",
  "pezeveng",
  "pezevengi",
  "pezevengin evladı",
  "pezevenk",
  "pezo",
  "pic",
  "pici",
  "picler",
  "pipi",
  "pipiş",
  "pisliktir",
  "piç",
  "piç kurusu",
  "piçin oğlu",
  "piçler",
  "porno",
  "pussy",
  "puşt",
  "puşttur",
  "rahminde",
  "revizyonist",
  "s1kerim",
  "s1kerm",
  "s1krm",
  "sakso",
  "saksofon",
  "salaak",
  "salak",
  "saxo",
  "sekis",
  "serefsiz",
  "sevgi koyarım",
  "sevişelim",
  "sexs",
  "sicarsin",
  "sie",
  "sik",
  "sikdi",
  "sikdiğim",
  "sike",
  "sikecem",
  "sikem",
  "siken",
  "sikenin",
  "siker",
  "sikerim",
  "sikerler",
  "sikersin",
  "sikertir",
  "sikertmek",
  "sikesen",
  "sikesicenin",
  "sikey",
  "sikeydim",
  "sikeyim",
  "sikeym",
  "siki",
  "sikicem",
  "sikici",
  "sikien",
  "sikienler",
  "sikiiim",
  "sikiiimmm",
  "sikiim",
  "sikiir",
  "sikiirken",
  "sikik",
  "sikil",
  "sikildiini",
  "sikilesice",
  "sikilmi",
  "sikilmie",
  "sikilmis",
  "sikilmiş",
  "sikilsin",
  "sikim",
  "sikimde",
  "sikimden",
  "sikime",
  "sikimi",
  "sikimiin",
  "sikimin",
  "sikimle",
  "sikimsonik",
  "sikimtrak",
  "sikin",
  "sikinde",
  "sikinden",
  "sikine",
  "sikini",
  "sikip",
  "sikis",
  "sikisek",
  "sikisen",
  "sikish",
  "sikismis",
  "sikitiin",
  "sikiyim",
  "sikiym",
  "sikiyorum",
  "sikiş",
  "sikişen",
  "sikişme",
  "sikkim",
  "sikko",
  "sikleri",
  "sikleriii",
  "sikli",
  "sikm",
  "sikmek",
  "sikmem",
  "sikmiler",
  "sikmisligim",
  "siksem",
  "sikseydin",
  "sikseyidin",
  "siksin",
  "siksinbaya",
  "siksinler",
  "siksiz",
  "siksok",
  "siksz",
  "sikt",
  "sikti",
  "siktigimin",
  "siktigiminin",
  "siktii",
  "siktiim",
  "siktiimin",
  "siktiiminin",
  "siktiler",
  "siktim",
  "siktimin",
  "siktiminin",
  "siktir",
  "siktir et",
  "siktir git",
  "siktir lan",
  "siktir ol git",
  "siktirgit",
  "siktirir",
  "siktiririm",
  "siktiriyor",
  "siktirolgit",
  "siktiğim",
  "siktiğimin",
  "siktiğiminin",
  "sittimin",
  "sittir",
  "skcem",
  "skecem",
  "skem",
  "sker",
  "skerim",
  "skerm",
  "skeyim",
  "skiim",
  "skik",
  "skim",
  "skime",
  "skmek",
  "sksin",
  "sksn",
  "sksz",
  "sktiimin",
  "sktrr",
  "skyim",
  "slaleni",
  "sokam",
  "sokarim",
  "sokarm",
  "sokarmkoduumun",
  "sokarım",
  "sokaym",
  "sokayım",
  "sokiim",
  "soktuğumunun",
  "sokuk",
  "sokum",
  "sokuyum",
  "sokuş",
  "soxum",
  "sulaleni",
  "sülaleni",
  "sülalenizi",
  "sürtük",
  "sıecem",
  "sıçarım",
  "sıçtığım",
  "taaklarn",
  "taaklarna",
  "tarrakimin",
  "tasak",
  "tassak",
  "taşak",
  "taşşak",
  "tipini s.k",
  "tipinizi s.keyim",
  "tiyniyat",
  "toplarm",
  "topsun",
  "totoş",
  "vajina",
  "vajinanı",
  "veled",
  "veled i zina",
  "veledizina",
  "verdiimin",
  "weled",
  "weledizina",
  "whore",
  "xikeyim",
  "yaaraaa",
  "yalama",
  "yalarun",
  "yalarım",
  "yaraaam",
  "yarak",
  "yaraksız",
  "yaraktr",
  "yaram",
  "yaraminbasi",
  "yaramn",
  "yararmorospunun",
  "yarra",
  "yarraaaa",
  "yarraak",
  "yarraam",
  "yarraamı",
  "yarragi",
  "yarragimi",
  "yarragina",
  "yarragindan",
  "yarragm",
  "yarraimin",
  "yarrak",
  "yarram",
  "yarramin",
  "yarraminbaşı",
  "yarramn",
  "yarran",
  "yarrana",
  "yarrağ",
  "yarrağım",
  "yarrağımı",
  "yarrrak",
  "yavak",
  "yavuşak",
  "yavş",
  "yavşak",
  "yavşaktır",
  "yilisik",
  "yogurtlayam",
  "yoğurtlayam",
  "yrrak",
  "yılışık",
  "zibidi",
  "zigsin",
  "zikeyim",
  "zikiiim",
  "zikiim",
  "zikik",
  "zikim",
  "ziksiiin",
  "ziksiin",
  "zulliyetini",
  "zviyetini",
  "zıkkımım",
  "çük",
  "öküz",
  "öşex",
  "ıbnelık",
  "şerefsiz",
  "şıllık"
];

// Spam kaliplari: link/telefon/e-posta/asiri tekrar
const SPAM_PATTERNS = [
  /https?:\/\//i,
  /www\./i,
  /\b\d{10,}\b/,
  /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/i,
  /(.)\1{6,}/,
];

function normalize(text) {
  return text
    .toLocaleLowerCase("tr-TR")
    .replace(/[^a-zçğıöşü0-9\s]/gi, " ");
}

function containsBlockedWord(text) {
  const normalized = normalize(text);
  const tokens = normalized.split(/\s+/).filter(Boolean);
  const tokenSet = new Set(tokens);
  return BLOCKED_WORDS.some((entry) => {
    if (entry.includes(" ")) {
      return normalized.includes(entry);
    }
    return tokenSet.has(entry);
  });
}

function matchesSpamPattern(text) {
  return SPAM_PATTERNS.some((pattern) => pattern.test(text));
}

function quickFilterReject(text) {
  return containsBlockedWord(text) || matchesSpamPattern(text);
}

module.exports = { quickFilterReject };
